### ISSUE TITLE
How to compare local (committed) images?

### ISSUE THREAD

**Issue by JoshMcCullough** [reproducible-containers/diffoci#93]
I'm likely missing something here but suppose I have a running container, `test` and I commit it via `docker commit -t test:before test`. Then I make changes to the running container and commit it again via `docker commit -t test:after test`.

How do I diff those local images? I have tried to do this:

```bash
./diffoci diff test:before test:after
```

Which complains that it cannot find the image or doesn't have authorization:
>FATA[0000] failed to pull "docker.io/library/test:before": failed to pull "docker.io/library/test:before": failed to resolve image: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed 

I've also tried using the `--backend=local` option (which I don't think is correct anyway), and I get the same issue.

**Comment by AkihiroSuda** [comment]
Try prepending docker:// to the image name
