### ISSUE TITLE
What's the reason for 4GiB tar size limit?

### ISSUE THREAD

**Issue by lacop** [reproducible-containers/diffoci#99]
I was trying to diff some large images and ran into the error `too large tar blob`.

This comes from:
https://github.com/reproducible-containers/diffoci/blob/5b173634a3d2fb90d77e6c552468e273c63672d2/pkg/diff/diff.go#L1046

Any reason for this limit? I built the tool locally with the limit increased to 16 GiB and it seems to work fine. Is this some inherent limitation, or just some sort of safety default?

If the latter, would you be open to accepting PR that either increases it, or at least adds a flag that allows overriding it?

**Comment by AkihiroSuda** [comment]
Just some sort of safety default.
Probably this should be customizable via a flag.

**Comment by AkihiroSuda** [comment]
@lacop Would you like to submit a PR? 🙂

**Comment by AkihiroSuda** [comment]
PR
- https://github.com/reproducible-containers/diffoci/pull/117
